name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to ACR
      uses: docker/login-action@v3
      with:
        registry: emsregistry.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t emsregistry.azurecr.io/php-ems:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push emsregistry.azurecr.io/php-ems:${{ github.sha }}